name       : python-ipaddr
version    : 2.1.11
release    : 1
source     :
    - https://pypi.python.org/packages/source/i/ipaddr/ipaddr-2.1.11.tar.gz : 1b555b8a8800134fdafe32b7d0cb52f5bdbfdd093707c3dd484c5ea59f1d98b7
license    : Apache-2.0
summary    : Google's IP address manipulation library
description: |
    ipaddr.py is a library for working with IP addresses, both IPv4 and IPv6. It was developed by Google for internal use, and is now open source.
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
